[DISCORD]
# Token del bot
TOKEN = 

# Canales (IDs de Discord)
CHANNEL_CHAT = 
CHANNEL_ADMIN = 
CHANNEL_BAN = 
CHANNEL_PERMIT = 

# Rol con permisos administrativos
ADMIN_ROLE = 


[RCON]
# Configuración del servidor Valheim
HOST = 
PORT = 
PASSWORD = 


[SYSTEM]
# Modos disponibles:
# GUI       = Panel visual (recomendado)
# TERMINAL  = Solo consola
# SERVICE   = Auto-reinicio (para servidores 24/7)
MODE = GUI